# Generated by Django 5.2.13 on 2026-04-25 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloc', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('capacite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.utilisateur')),
                ('is_chef_departement', models.BooleanField(default=False)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='core.departement')),
            ],
            bases=('users.utilisateur',),
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('License', 'Cours'), ('Master', 'Td'), ('Doctorat', 'Tp')], max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('semestre', models.IntegerField()),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Sceance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CM', 'Cours'), ('TD', 'TD'), ('TP', 'TP')], max_length=50)),
                ('duration', models.IntegerField()),
                ('nombre_sceances', models.IntegerField()),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sceances', to='core.enseignant')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sceances', to='core.local')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sceances', to='core.module')),
            ],
        ),
    ]
