# Generated by Django 5.2.14 on 2026-05-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceanceSimulee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques')], max_length=10)),
                ('duree', models.IntegerField()),
                ('date', models.DateField()),
                ('volumeActuel', models.IntegerField()),
                ('volumePrevu', models.IntegerField()),
                ('variation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomScenario', models.CharField(max_length=100)),
                ('anneeCible', models.IntegerField()),
                ('estValide', models.BooleanField(default=False)),
                ('utiliserVolumesActuels', models.BooleanField(default=True)),
                ('utiliserMoyenneDepartement', models.BooleanField(default=False)),
                ('inclureNouvellesFilieres', models.BooleanField(default=False)),
                ('inclureNouveauxModules', models.BooleanField(default=False)),
                ('volumeTotalPrevu', models.IntegerField(default=0)),
                ('tauxEvolutionGlobal', models.FloatField(default=0.0)),
            ],
        ),
    ]
