# Generated by Django 5.2.14 on 2026-05-17 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyse_vh', '0001_initial'),
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceancesimulee',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sceances_simulees', to='users.enseignant'),
        ),
        migrations.AddField(
            model_name='sceancesimulee',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sceances_simulees', to='core.local'),
        ),
        migrations.AddField(
            model_name='sceancesimulee',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sceances_simulees', to='core.module'),
        ),
        migrations.AddField(
            model_name='sceancesimulee',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sceances_simulees', to='analyse_vh.simulation'),
        ),
    ]
