# Generated by Django 6.0.5 on 2026-06-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_vh', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='tauxEvolutionGlobal',
            new_name='croissance_etudiante_pct',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='volumeTotalPrevu',
            new_name='deficit_horaire',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='utiliserVolumesActuels',
            new_name='utiliser_donnees_actuelles',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='inclureNouveauxModules',
            new_name='utiliser_moyenne_departement',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='inclureNouvellesFilieres',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='utiliserMoyenneDepartement',
        ),
        migrations.AddField(
            model_name='simulation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='moyenne_charge_actuelle',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='moyenne_charge_prevue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='nb_filieres_ajoutees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='nb_locaux_ajoutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='nb_nouveaux_cours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='nb_profs_ajoutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='nb_vacataires_estimes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='result_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='strategie_traitement',
            field=models.CharField(choices=[('EQUITE', 'Équité (Charge équilibrée)'), ('JUNIOR', 'Junior (Priorité TD/TP)'), ('SENIOR', 'Senior (Priorité CM)'), ('ALLEGEMENT', 'Allégement (Réduction de charge globale)')], default='EQUITE', max_length=20),
        ),
        migrations.AddField(
            model_name='simulation',
            name='volume_actuel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='volume_total_prevu',
            field=models.IntegerField(default=0),
        ),
    ]
