# Generated by Django 6.0.5 on 2026-06-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_vh', '0003_rename_tauxevolutionglobal_simulation_croissance_etudiante_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='message',
            field=models.CharField(default='Prêt', max_length=255),
        ),
        migrations.AddField(
            model_name='simulation',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
