# Generated by Django 6.0.5 on 2026-06-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_vh', '0004_simulation_message_simulation_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='periode',
            field=models.CharField(default='autumn', max_length=10),
        ),
    ]
