# Generated by Django 5.2.14 on 2026-05-17 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('motDePasse', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('CHEF_DEPARTEMENT', 'Chef de Département'), ('ENSEIGNANT', 'Enseignant')], default='ENSEIGNANT', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.utilisateur')),
            ],
            bases=('users.utilisateur',),
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.utilisateur')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignants_list', to='core.departement')),
                ('modules', models.ManyToManyField(blank=True, related_name='enseignants_habilites', to='core.module')),
            ],
            bases=('users.utilisateur',),
        ),
        migrations.CreateModel(
            name='ChefDepartement',
            fields=[
                ('enseignant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.enseignant')),
            ],
            bases=('users.enseignant',),
        ),
    ]
