# Generated by Django 5.2.14 on 2026-06-01 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_vh', '0002_initial'),
        ('core', '0014_local_is_amphi'),
        ('users', '0003_utilisateur_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefdepartement',
            name='enseignant_ptr',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='utilisateur_ptr',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_list', to='core.departement'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='users_habilites', to='core.module'),
        ),
        migrations.DeleteModel(
            name='Administrateur',
        ),
        migrations.DeleteModel(
            name='ChefDepartement',
        ),
        migrations.DeleteModel(
            name='Enseignant',
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.utilisateur',),
        ),
        migrations.CreateModel(
            name='ChefDepartement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.utilisateur',),
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.utilisateur',),
        ),
    ]
