# Generated by Django 6.0.5 on 2026-07-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_chefdepartement_enseignant_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('CHEF_DEPARTEMENT', 'Chef de Département'), ('RESPONSABLE_FILIERE', 'Responsable de Filière'), ('ENSEIGNANT', 'Enseignant'), ('UTILISATEUR', 'Utilisateur')], default='ENSEIGNANT', max_length=20),
        ),
    ]
