# Generated by Django 6.0.5 on 2026-07-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_utilisateur_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='specialite',
            field=models.CharField(blank=True, choices=[('INFORMATIQUE', 'Informatique'), ('MATHEMATIQUES', 'Mathématiques'), ('PHYSIQUE', 'Physique'), ('LANGUES', 'Langues'), ('AUTRE', 'Autre')], default='INFORMATIQUE', max_length=50, null=True),
        ),
    ]
