# Generated by Django 6.0.5 on 2026-07-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_utilisateur_specialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(default='ENSEIGNANT', max_length=100),
        ),
    ]
