# Generated by Django 5.2.14 on 2026-05-17 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='chef',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_gere', to='users.chefdepartement'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='core.departement'),
        ),
        migrations.AddField(
            model_name='comporte',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filiere'),
        ),
        migrations.AddField(
            model_name='local',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locaux', to='core.departement'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='modules',
            field=models.ManyToManyField(related_name='filieres', through='core.Comporte', to='core.module'),
        ),
        migrations.AddField(
            model_name='comporte',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.module'),
        ),
        migrations.AddField(
            model_name='sceance',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sceances', to='users.enseignant'),
        ),
        migrations.AddField(
            model_name='sceance',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sceances', to='core.local'),
        ),
        migrations.AddField(
            model_name='sceance',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sceances', to='core.module'),
        ),
        migrations.AlterUniqueTogether(
            name='comporte',
            unique_together={('filiere', 'module')},
        ),
    ]
