# Generated by Django 5.2.14 on 2026-05-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comporte',
            name='semestre',
            field=models.CharField(choices=[('S1_l', 'S1 L')], max_length=50),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='niveaux',
            field=models.CharField(choices=[('Licence_f', 'Licence Fondamontale'), ('Licence_e', 'Licence Excellence'), ('Licence_t', 'Licence temps amenagé'), ('Master_f', 'Master Fondamontale'), ('Master_e', 'Master Excellence'), ('Master_t', 'Master temps amenagé')], max_length=20),
        ),
    ]
