# Generated by Django 6.0.5 on 2026-05-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comporte_semestre_alter_filiere_niveaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
