# Generated by Django 5.2.14 on 2026-05-28 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_filiere_description'),
        ('users', '0002_utilisateur_langue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_conge', models.CharField(max_length=100)),
                ('statut', models.CharField(default='Pending', max_length=20)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='users.enseignant')),
            ],
        ),
    ]
