# Generated by Django 5.2.14 on 2026-05-28 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vacation'),
        ('users', '0002_utilisateur_langue'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacation',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='users.enseignant'),
        ),
    ]
