# Generated by Django 5.2.14 on 2026-05-28 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vacation_is_global_vacation_titre_and_more'),
        ('users', '0002_utilisateur_langue'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceance',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sceance',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sceances', to='users.enseignant'),
        ),
    ]
