# Generated by Django 5.2.14 on 2026-05-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_comporte_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6'), ('M1', 'Semestre 7 (M1)'), ('M2', 'Semestre 8 (M2)'), ('M3', 'Semestre 9 (M3)'), ('M4', 'Semestre 10 (M4)')], max_length=10, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
    ]
