# Generated by Django 5.2.14 on 2026-05-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_semesterperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='numero',
            field=models.CharField(max_length=100),
        ),
    ]
