# Generated by Django 5.2.14 on 2026-05-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_local_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='comporte',
            name='v_h_hebdo',
            field=models.IntegerField(default=2),
        ),
    ]
