# Generated by Django 6.0.5 on 2026-05-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_scheduletask_result_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='is_amphi',
            field=models.BooleanField(default=False),
        ),
    ]
