# Generated by Django 6.0.5 on 2026-07-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_sceance_enseignant_alter_vacation_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='seuil_horaire',
            field=models.IntegerField(default=192),
        ),
    ]
